// examples/spa/angular/src/app/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core'
import {NgTemplateOutlet} from '@angular/common'
import {
  activities,
  documentTitle,
  memberFromHash,
  members,
  metrics,
  normalizeHash,
  overviewDetails,
  projects,
  routeFromHash,
  type ProjectFilter,
  type Route,
  type Toast,
} from '../../../data'
import {
  filterLargeRecords,
  orderLargeRecords,
  recordFilters,
  type RecordFilter,
  type RecordSortDirection,
} from '../../../data-20k'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NgTemplateOutlet],
  templateUrl: './app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly projects = projects
  readonly activities = activities
  readonly members = members
  readonly metrics = metrics
  readonly filters: readonly ProjectFilter[] = ['all', 'active', 'planning']
  readonly recordFilters = recordFilters
  readonly weekdays = [
    'Mon',
    'Tue',
    'Wed',
    'Thu',
    'Fri',
    'Sat',
    'Sun',
  ] as const

  readonly route = signal<Route>('overview')
  readonly memberId = signal<string | null>(null)
  readonly navOpen = signal(false)
  readonly filter = signal<ProjectFilter>('all')
  readonly recordFilter = signal<RecordFilter>('all')
  readonly recordSort = signal<RecordSortDirection>('ascending')
  readonly toasts = signal<Toast[]>([])
  readonly emailError = signal('')
  readonly now = signal(new Date())
  readonly overview = computed(() => overviewDetails(this.now()))

  readonly selectedMember = computed(() => {
    return this.members.find(member => member.id === this.memberId())
  })
  readonly visibleProjects = computed(() => {
    return this.projects.filter(project => {
      return this.filter() === 'all'
        || project.status.toLowerCase() === this.filter()
    })
  })
  readonly visibleRecords = computed(() => {
    return orderLargeRecords(
      filterLargeRecords(this.recordFilter()),
      this.recordSort(),
    )
  })

  private readonly destroyRef = inject(DestroyRef)
  private readonly toastTimers = new Map<string, number>()
  private nextToastId = 1

  constructor() {
    normalizeHash()
    this.readHash()

    const handleHashChange = () => {
      this.readHash()
      this.navOpen.set(false)
      this.toasts.set([])
      document.querySelector<HTMLElement>('main')?.focus({preventScroll: true})
    }

    addEventListener('hashchange', handleHashChange)
    const clock = window.setInterval(() => this.now.set(new Date()), 60_000)
    this.destroyRef.onDestroy(() => {
      removeEventListener('hashchange', handleHashChange)
      window.clearInterval(clock)
      this.toastTimers.forEach(timer => clearTimeout(timer))
    })

    effect(() => {
      document.title = documentTitle(this.route(), this.memberId())
    })
  }

  closeIfCurrent(route: Route): void {
    if (this.route() === route) this.navOpen.set(false)
  }

  setFilter(filter: ProjectFilter): void {
    this.filter.set(filter)
  }

  setRecordFilter(filter: RecordFilter): void {
    this.recordFilter.set(filter)
  }

  toggleRecordSort(): void {
    this.recordSort.update(direction => {
      return direction === 'ascending' ? 'descending' : 'ascending'
    })
  }

  submitInvite(e: SubmitEvent): void {
    e.preventDefault()
    const form = e.currentTarget as HTMLFormElement
    const input = form.elements.namedItem('email') as HTMLInputElement
    input.value = input.value.trim()
    const message = this.validationMessage(input)
    this.emailError.set(message)

    if (message !== '') {
      input.focus()
      return
    }
    this.showToast()
  }

  submitDemo(e: SubmitEvent): void {
    e.preventDefault()
    this.showToast()
  }

  updateEmailError(e: Event): void {
    if (this.emailError() !== '') {
      this.emailError.set(this.validationMessage(e.currentTarget as HTMLInputElement))
    }
  }

  showToast(): void {
    const toast = {
      id: `toast-${this.nextToastId++}`,
      message: 'No server for demo',
    }
    this.toasts.update(items => [...items, toast])
    this.toastTimers.set(
      toast.id,
      window.setTimeout(() => this.dismissToast(toast.id), 3200),
    )
  }

  dismissToast(id: string): void {
    clearTimeout(this.toastTimers.get(id))
    this.toastTimers.delete(id)
    this.toasts.update(items => items.filter(item => item.id !== id))
  }

  private readHash(): void {
    this.route.set(routeFromHash(location.hash))
    this.memberId.set(memberFromHash(location.hash))
  }

  private validationMessage(input: HTMLInputElement): string {
    if (input.validity.valueMissing) return 'Enter an email address.'
    if (input.validity.typeMismatch) return 'Enter a valid email address.'
    return ''
  }
}

<div id="shell" [attr.data-navigation-state]="navOpen() ? 'open' : null">
  <div id="header">
    <header id="topbar">
      <div class="start">
        <button id="menu" class="icon-button" type="button" aria-label="Open navigation" aria-controls="navigation" [attr.aria-expanded]="navOpen()" (click)="navOpen.set(!navOpen())">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"></path></svg>
        </button>
        <a class="brand" href="#/overview" aria-label="Luminate overview">
          <svg class="mark" viewBox="0 0 36 36" aria-hidden="true"><path d="M18 3l3.6 11.4L33 18l-11.4 3.6L18 33l-3.6-11.4L3 18l11.4-3.6L18 3Z"></path><circle cx="18" cy="18" r="3.8"></circle></svg>
          <span>luminate</span>
        </a>
        <span class="divider" aria-hidden="true"></span>
        <div class="workspace-switcher"><span class="avatar">N</span><span class="name">Luminate</span></div>
      </div>
      <div class="end"><a class="user-menu" href="#/teams/freddy-fraggin"><span class="avatar">FF</span><span class="name">Freddy Fraggin</span></a></div>
    </header>
  </div>

  <aside id="sidebar">
    <nav id="navigation" aria-label="Primary navigation">
      <div class="body">
        <p class="eyebrow">Workspace</p>
        <a class="link" href="#/overview" [attr.aria-current]="route() === 'overview' ? 'page' : null" (click)="closeIfCurrent('overview')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="6" height="6" rx="1"></rect><rect x="14" y="4" width="6" height="6" rx="1"></rect><rect x="4" y="14" width="6" height="6" rx="1"></rect><rect x="14" y="14" width="6" height="6" rx="1"></rect></svg>
          <span>Overview</span>
        </a>
        <a class="link" href="#/projects" [attr.aria-current]="route() === 'projects' ? 'page' : null" (click)="closeIfCurrent('projects')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z"></path></svg>
          <span>Projects</span><span class="count">{{ projects.length }}</span>
        </a>
        <a class="link" href="#/records" [attr.aria-current]="route() === 'records' ? 'page' : null" (click)="closeIfCurrent('records')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h14M5 12h14M5 19h14"></path></svg><span>Records</span>
        </a>
        <a class="link" href="#/activity" [attr.aria-current]="route() === 'activity' ? 'page' : null" (click)="closeIfCurrent('activity')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h3l2-6 4 12 2-6h5"></path></svg><span>Activity</span>
        </a>
        <p class="eyebrow manage">Manage</p>
        <a class="link" href="#/teams" [attr.aria-current]="route() === 'teams' ? 'page' : null" (click)="closeIfCurrent('teams')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M16 8h5M18.5 5.5v5"></path></svg><span>Teams</span>
        </a>
      </div>
    </nav>
  </aside>

  <button id="backdrop" type="button" aria-label="Close navigation" (click)="navOpen.set(false)"></button>

  <main tabindex="-1">
    @if (route() === 'overview') {
      <section id="overview" aria-labelledby="overview-title">
        <div class="heading">
          <div><p class="eyebrow">{{ overview().date }}</p><h1 id="overview-title">{{ overview().title }}</h1><p>Here's what's happening across your workspace today.</p></div>
          <a class="primary-button" href="#/projects"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z"></path></svg>View projects</a>
        </div>
        <div class="metric-grid">
          @for (metric of metrics; track metric.id) {
            <article class="metric-card" [attr.data-direction]="metric.direction">
              <div class="top"><span>{{ metric.label }}</span></div><strong>{{ metric.value }}</strong><span class="change">{{ metric.change }}</span>
            </article>
          }
        </div>
        <section class="focus">
          <div class="heading"><div><h2>In focus</h2><p>Your team's most active projects.</p></div><a class="text-link" href="#/projects">View all <span aria-hidden="true">→</span></a></div>
          <div class="project-grid">
            @for (project of projects.slice(0, 3); track project.id) {
              <ng-container [ngTemplateOutlet]="projectCard" [ngTemplateOutletContext]="{$implicit: project}"></ng-container>
            }
          </div>
        </section>
        <div class="overview-lower">
          <section class="panel activity-panel" aria-labelledby="recent-activity-title">
            <div class="heading"><div><h2 id="recent-activity-title">Recent activity</h2><p>The latest updates from your team.</p></div><a class="text-link" href="#/activity">See all</a></div>
            <ol class="activity-list">
              @for (activity of activities.slice(0, 3); track activity.id) {
                <ng-container [ngTemplateOutlet]="activityItem" [ngTemplateOutletContext]="{$implicit: activity}"></ng-container>
              }
            </ol>
          </section>
          <aside class="panel week-card" aria-labelledby="week-title">
            <div class="top"><p class="eyebrow">This week</p><h2 id="week-title">Strong momentum</h2><p>Your team completed 28% more work than last week.</p></div>
            <div class="week-chart" aria-label="Weekly activity chart">
              @for (day of weekdays; track day) {
                <span [attr.data-day-state]="day === overview().today ? 'today' : null"><i>{{ day }}</i></span>
              }
            </div>
          </aside>
        </div>
      </section>
    } @else if (route() === 'projects') {
      <section id="projects" aria-labelledby="projects-title">
        <div class="heading"><div><p class="eyebrow">Workspace</p><h1 id="projects-title">Projects</h1><p>Plan work, track progress, and keep the team aligned.</p></div></div>
        <div class="project-toolbar">
          <div class="filters" aria-label="Filter projects">
            @for (value of filters; track value) {
              <button type="button" [attr.aria-pressed]="filter() === value" (click)="setFilter(value)">{{ value[0].toUpperCase() + value.slice(1) }}</button>
            }
          </div>
          <p>{{ visibleProjects().length }} {{ visibleProjects().length === 1 ? 'project' : 'projects' }} shown</p>
        </div>
        <div class="project-grid">
          @for (project of visibleProjects(); track project.id) {
            <ng-container [ngTemplateOutlet]="projectCard" [ngTemplateOutletContext]="{$implicit: project}"></ng-container>
          }
        </div>
      </section>
    } @else if (route() === 'records') {
      <section id="records" aria-labelledby="records-title">
        <div class="heading"><div><p class="eyebrow">Performance dataset</p><h1 id="records-title">Records</h1><p>Filter and sort a deterministic 20,000-row dataset without virtualization.</p></div></div>
        <div class="record-toolbar">
          <div class="filters" aria-label="Filter records">
            @for (value of recordFilters; track value) {
              <button type="button" [attr.data-record-filter]="value" [attr.aria-pressed]="recordFilter() === value" (click)="setRecordFilter(value)">{{ value[0].toUpperCase() + value.slice(1) }}</button>
            }
          </div>
          <p class="record-summary">{{ visibleRecords().length.toLocaleString('en-US') }} records shown</p>
        </div>
        <div class="record-list-wrap panel">
          <div class="record-list-header" [attr.aria-sort]="recordSort()">
            <button type="button" data-record-sort (click)="toggleRecordSort()">
              Record <span class="record-sort-indicator" aria-hidden="true">{{ recordSort() === 'ascending' ? '↑' : '↓' }}</span>
            </button>
          </div>
          <ol class="record-list">
            @for (record of visibleRecords(); track record.id) {
              <li class="record-row">{{ record.label }}</li>
            }
          </ol>
        </div>
      </section>
    } @else if (route() === 'activity') {
      <section id="activity" aria-labelledby="activity-title">
        <div class="heading"><div><p class="eyebrow">Workspace</p><h1 id="activity-title">Team activity</h1><p>A shared record of progress across every project.</p></div><span class="count">{{ activities.length }} updates</span></div>
        <div class="activity-layout">
          <section class="panel activity-panel" aria-label="All activity">
            <div class="activity-date"><span>Today</span><span class="line"></span></div>
            <ol class="activity-list">
              @for (activity of activities; track activity.id) {
                <ng-container [ngTemplateOutlet]="activityItem" [ngTemplateOutletContext]="{$implicit: activity}"></ng-container>
              }
            </ol>
          </section>
          <aside class="activity-summary">
            <section class="panel summary-card"><p class="eyebrow">Last 7 days</p><strong>42</strong><span>team updates</span><div class="mini-bars" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div></section>
            <section class="panel contributor-card"><p class="eyebrow">Top contributors</p><div><span class="avatar" data-person="norm-barlug">NB</span><a href="#/teams/norm-barlug">Norm Barlug</a><em>14</em></div><div><span class="avatar" data-person="emmy-nother">EN</span><a href="#/teams/emmy-nother">Emmy Nother</a><em>11</em></div><div><span class="avatar" data-person="fazlo-kan">FK</span><a href="#/teams/fazlo-kan">Fazlo Kan</a><em>9</em></div></section>
          </aside>
        </div>
      </section>
    } @else {
      <section id="teams">
        @if (selectedMember(); as member) {
          <div id="profile">
            <a class="back-link" href="#/teams"><span aria-hidden="true">←</span> All team members</a>
            <article class="panel member-profile-card">
              <div class="header"><span class="avatar large" [attr.data-person]="member.id">{{ member.initials }}</span><div><p class="eyebrow">{{ member.team }}</p><h1>{{ member.name }}</h1><span>{{ member.role }}</span></div></div>
              <p class="bio">{{ member.bio }}</p>
              <dl class="member-details"><div><dt>Email</dt><dd><a [href]="'mailto:' + member.email">{{ member.email }}</a></dd></div><div><dt>Country</dt><dd>{{ member.country }}</dd></div><div><dt>Team</dt><dd>{{ member.team }}</dd></div></dl>
            </article>
          </div>
        } @else {
          <div>
            <div class="heading"><div><p class="eyebrow">Manage</p><h1 id="teams-title">Manage teams</h1><p>Invite people and organize how your workspace collaborates.</p></div><span class="count">{{ members.length }} members</span></div>
            <section class="panel member-directory" aria-labelledby="member-list-title">
              <div class="heading"><div><h2 id="member-list-title">All team members</h2><p>Everyone with access to the Luminate workspace.</p></div><span>Team</span><span>Role</span></div>
              <div class="member-list">
                @for (member of members; track member.id) {
                  <article class="member-row"><span class="avatar" [attr.data-person]="member.id">{{ member.initials }}</span><div class="identity"><a [href]="'#/teams/' + member.id">{{ member.name }}</a><span>{{ member.email }}</span></div><span class="team">{{ member.team }}</span><span class="role">{{ member.role }}</span></article>
                }
              </div>
            </section>
            <section class="team-actions">
              <div class="heading"><div><h2>Team actions</h2><p>Invitations and new teams require a connected server.</p></div></div>
              <div class="forms">
                <form class="panel team-form" novalidate (submit)="submitInvite($event)">
                  <div class="heading"><span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M17.5 8v6M14.5 11h6"></path></svg></span><div><h2>Invite a teammate</h2><p>Send an invitation to join Luminate.</p></div></div>
                  <label class="field"><span>Email address</span><input type="email" name="email" placeholder="name@company.com" aria-describedby="invite-email-error" [attr.aria-invalid]="emailError() ? 'true' : null" required (input)="updateEmailError($event)"><small id="invite-email-error" class="error" aria-live="polite" [hidden]="!emailError()">{{ emailError() }}</small></label>
                  <label class="field"><span>Role</span><select name="role"><option>Member</option><option>Admin</option><option>Viewer</option></select></label>
                  <button class="primary-button" type="submit">Send invitation</button>
                </form>
                <form class="panel team-form" novalidate (submit)="submitDemo($event)">
                  <div class="heading"><span class="icon" data-form-kind="create-team" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="8" cy="8" r="3"></circle><circle cx="17" cy="9" r="2.5"></circle><path d="M2.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M14 14c3.8-.7 6.2 1 6.8 5"></path></svg></span><div><h2>Create a team</h2><p>Group teammates around a shared area of work.</p></div></div>
                  <label class="field"><span>Team name</span><input type="text" name="teamName" placeholder="e.g. Product design" required></label>
                  <label class="field"><span>Description <em>Optional</em></span><textarea name="description" rows="3" placeholder="What does this team work on?"></textarea></label>
                  <button class="primary-button" type="submit">Create team</button>
                </form>
              </div>
            </section>
          </div>
        }
        <div id="toasts" aria-live="polite" aria-label="Notifications">
          @for (toast of toasts(); track toast.id) {
            <div class="toast"><span class="icon" aria-hidden="true">!</span><span class="message">{{ toast.message }}</span><button type="button" aria-label="Dismiss notification" (click)="dismissToast(toast.id)">×</button></div>
          }
        </div>
      </section>
    }
  </main>
</div>

<ng-template #projectCard let-project>
  <article class="project-card">
    <div class="top"><span class="accent" [attr.data-project]="project.id"></span><span class="status" [attr.data-status]="project.status">{{ project.status }}</span></div>
    <h3>{{ project.name }}</h3><p>{{ project.description }}</p>
    <div class="progress-label"><span>Progress</span><strong>{{ project.progress }}%</strong></div>
    <div class="progress-track"><span class="bar" [attr.data-project]="project.id"></span></div>
    <div class="footer"><span class="members">{{ project.members }}</span><span>{{ project.due }}</span></div>
  </article>
</ng-template>

<ng-template #activityItem let-activity>
  <li class="activity-item">
    <span class="avatar" [attr.data-person]="activity.personId">{{ activity.initials }}</span>
    <div class="copy"><p><a class="person" [href]="'#/teams/' + activity.personId">{{ activity.person }}</a> <span>{{ activity.action }}</span> <b>{{ activity.target }}</b></p><time>{{ activity.time }}</time></div>
  </li>
</ng-template>

// examples/spa/vue/src/App.vue
<script setup lang="ts">
import {computed, onBeforeUnmount, onMounted, ref, watch} from 'vue'
import ActivityList from './components/ActivityList.vue'
import ProjectCards from './components/ProjectCards.vue'
import {
  activities,
  documentTitle,
  memberFromHash,
  members,
  metrics,
  normalizeHash,
  overviewDetails,
  projects,
  routeFromHash,
  type ProjectFilter,
  type Toast,
} from '../../data'
import {
  filterLargeRecords,
  orderLargeRecords,
  recordFilters,
  type RecordFilter,
  type RecordSortDirection,
} from '../../data-20k'

normalizeHash()

const route = ref(routeFromHash(location.hash))
const memberId = ref(memberFromHash(location.hash))
const navOpen = ref(false)
const filter = ref<ProjectFilter>('all')
const recordFilter = ref<RecordFilter>('all')
const recordSort = ref<RecordSortDirection>('ascending')
const toasts = ref<Toast[]>([])
const emailError = ref('')
const now = ref(new Date())
let nextToastId = 1
let clock: number | undefined
const toastTimers = new Map<string, number>()

const selectedMember = computed(() => members.find(member => member.id === memberId.value))
const visibleProjects = computed(() => projects.filter(project => {
  return filter.value === 'all' || project.status.toLowerCase() === filter.value
}))
const visibleRecords = computed(() => orderLargeRecords(
  filterLargeRecords(recordFilter.value),
  recordSort.value,
))
const overview = computed(() => overviewDetails(now.value))

function handleHashChange() {
  route.value = routeFromHash(location.hash)
  memberId.value = memberFromHash(location.hash)
  navOpen.value = false
  toasts.value = []
  document.querySelector<HTMLElement>('main')?.focus({preventScroll: true})
}

function closeIfCurrent(name: typeof route.value) {
  if (route.value === name) navOpen.value = false
}

function showToast() {
  const toast = {id: `toast-${nextToastId++}`, message: 'No server for demo'}
  toasts.value.push(toast)
  toastTimers.set(toast.id, window.setTimeout(() => dismissToast(toast.id), 3200))
}

function dismissToast(id: string) {
  clearTimeout(toastTimers.get(id))
  toastTimers.delete(id)
  toasts.value = toasts.value.filter(toast => toast.id !== id)
}

function validateEmail(input: HTMLInputElement) {
  return input.validity.valueMissing
    ? 'Enter an email address.'
    : input.validity.typeMismatch
      ? 'Enter a valid email address.'
      : ''
}

function submitInvite(e: Event) {
  const form = e.currentTarget as HTMLFormElement
  const input = form.elements.namedItem('email') as HTMLInputElement
  input.value = input.value.trim()
  emailError.value = validateEmail(input)
  if (emailError.value) {
    input.focus()
    return
  }
  showToast()
}

function updateEmailError(e: Event) {
  if (emailError.value) emailError.value = validateEmail(e.currentTarget as HTMLInputElement)
}

watch([route, memberId], () => {
  document.title = documentTitle(route.value, memberId.value)
}, {immediate: true})

onMounted(() => {
  addEventListener('hashchange', handleHashChange)
  clock = window.setInterval(() => {
    now.value = new Date()
  }, 60_000)
})
onBeforeUnmount(() => {
  removeEventListener('hashchange', handleHashChange)
  clearInterval(clock)
  toastTimers.forEach(timer => clearTimeout(timer))
})
</script>

<template>
  <div id="shell" :data-navigation-state="navOpen ? 'open' : undefined">
    <div id="header">
      <header id="topbar">
        <div class="start">
          <button id="menu" class="icon-button" type="button" aria-label="Open navigation" aria-controls="navigation" :aria-expanded="navOpen" @click="navOpen = !navOpen">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" /></svg>
          </button>
          <a class="brand" href="#/overview" aria-label="Luminate overview">
            <svg class="mark" viewBox="0 0 36 36" aria-hidden="true"><path d="M18 3l3.6 11.4L33 18l-11.4 3.6L18 33l-3.6-11.4L3 18l11.4-3.6L18 3Z" /><circle cx="18" cy="18" r="3.8" /></svg>
            <span>luminate</span>
          </a>
          <span class="divider" aria-hidden="true" />
          <div class="workspace-switcher"><span class="avatar">N</span><span class="name">Luminate</span></div>
        </div>
        <div class="end"><a class="user-menu" href="#/teams/freddy-fraggin"><span class="avatar">FF</span><span class="name">Freddy Fraggin</span></a></div>
      </header>
    </div>

    <aside id="sidebar">
      <nav id="navigation" aria-label="Primary navigation">
        <div class="body">
          <p class="eyebrow">Workspace</p>
          <a class="link" href="#/overview" :aria-current="route === 'overview' ? 'page' : undefined" @click="closeIfCurrent('overview')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="6" height="6" rx="1" /><rect x="14" y="4" width="6" height="6" rx="1" /><rect x="4" y="14" width="6" height="6" rx="1" /><rect x="14" y="14" width="6" height="6" rx="1" /></svg>
            <span>Overview</span>
          </a>
          <a class="link" href="#/projects" :aria-current="route === 'projects' ? 'page' : undefined" @click="closeIfCurrent('projects')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z" /></svg>
            <span>Projects</span><span class="count">{{ projects.length }}</span>
          </a>
          <a class="link" href="#/records" :aria-current="route === 'records' ? 'page' : undefined" @click="closeIfCurrent('records')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 5h14M5 12h14M5 19h14" /></svg><span>Records</span>
          </a>
          <a class="link" href="#/activity" :aria-current="route === 'activity' ? 'page' : undefined" @click="closeIfCurrent('activity')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h3l2-6 4 12 2-6h5" /></svg><span>Activity</span>
          </a>
          <p class="eyebrow manage">Manage</p>
          <a class="link" href="#/teams" :aria-current="route === 'teams' ? 'page' : undefined" @click="closeIfCurrent('teams')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3" /><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M16 8h5M18.5 5.5v5" /></svg><span>Teams</span>
          </a>
        </div>
      </nav>
    </aside>

    <button id="backdrop" type="button" aria-label="Close navigation" @click="navOpen = false" />

    <main tabindex="-1">
      <section v-if="route === 'overview'" id="overview" aria-labelledby="overview-title">
        <div class="heading">
          <div><p class="eyebrow">{{ overview.date }}</p><h1 id="overview-title">{{ overview.title }}</h1><p>Here's what's happening across your workspace today.</p></div>
          <a class="primary-button" href="#/projects"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z" /></svg>View projects</a>
        </div>
        <div class="metric-grid">
          <article v-for="metric in metrics" :key="metric.id" class="metric-card" :data-direction="metric.direction">
            <div class="top"><span>{{ metric.label }}</span></div><strong>{{ metric.value }}</strong><span class="change">{{ metric.change }}</span>
          </article>
        </div>
        <section class="focus">
          <div class="heading"><div><h2>In focus</h2><p>Your team's most active projects.</p></div><a class="text-link" href="#/projects">View all <span aria-hidden="true">→</span></a></div>
          <ProjectCards :items="projects.slice(0, 3)" />
        </section>
        <div class="overview-lower">
          <section class="panel activity-panel" aria-labelledby="recent-activity-title">
            <div class="heading"><div><h2 id="recent-activity-title">Recent activity</h2><p>The latest updates from your team.</p></div><a class="text-link" href="#/activity">See all</a></div>
            <ActivityList :items="activities.slice(0, 3)" />
          </section>
          <aside class="panel week-card" aria-labelledby="week-title">
            <div class="top"><p class="eyebrow">This week</p><h2 id="week-title">Strong momentum</h2><p>Your team completed 28% more work than last week.</p></div>
            <div class="week-chart" aria-label="Weekly activity chart">
              <span :data-day-state="overview.today === 'Mon' ? 'today' : undefined"><i>Mon</i></span><span :data-day-state="overview.today === 'Tue' ? 'today' : undefined"><i>Tue</i></span><span :data-day-state="overview.today === 'Wed' ? 'today' : undefined"><i>Wed</i></span><span :data-day-state="overview.today === 'Thu' ? 'today' : undefined"><i>Thu</i></span><span :data-day-state="overview.today === 'Fri' ? 'today' : undefined"><i>Fri</i></span><span :data-day-state="overview.today === 'Sat' ? 'today' : undefined"><i>Sat</i></span><span :data-day-state="overview.today === 'Sun' ? 'today' : undefined"><i>Sun</i></span>
            </div>
          </aside>
        </div>
      </section>

      <section v-else-if="route === 'projects'" id="projects" aria-labelledby="projects-title">
        <div class="heading"><div><p class="eyebrow">Workspace</p><h1 id="projects-title">Projects</h1><p>Plan work, track progress, and keep the team aligned.</p></div></div>
        <div class="project-toolbar">
          <div class="filters" aria-label="Filter projects">
            <button v-for="value in (['all', 'active', 'planning'] as const)" :key="value" type="button" :aria-pressed="filter === value" @click="filter = value">{{ value[0].toUpperCase() + value.slice(1) }}</button>
          </div>
          <p>{{ visibleProjects.length }} {{ visibleProjects.length === 1 ? 'project' : 'projects' }} shown</p>
        </div>
        <ProjectCards :items="visibleProjects" />
      </section>

      <section v-else-if="route === 'records'" id="records" aria-labelledby="records-title">
        <div class="heading"><div><p class="eyebrow">Performance dataset</p><h1 id="records-title">Records</h1><p>Filter and sort a deterministic 20,000-row dataset without virtualization.</p></div></div>
        <div class="record-toolbar">
          <div class="filters" aria-label="Filter records">
            <button v-for="value in recordFilters" :key="value" type="button" :data-record-filter="value" :aria-pressed="recordFilter === value" @click="recordFilter = value">{{ value[0].toUpperCase() + value.slice(1) }}</button>
          </div>
          <p class="record-summary">{{ visibleRecords.length.toLocaleString('en-US') }} records shown</p>
        </div>
        <div class="record-list-wrap panel">
          <div class="record-list-header" :aria-sort="recordSort">
            <button type="button" data-record-sort @click="recordSort = recordSort === 'ascending' ? 'descending' : 'ascending'">
              Record <span class="record-sort-indicator" aria-hidden="true">{{ recordSort === 'ascending' ? '↑' : '↓' }}</span>
            </button>
          </div>
          <ol class="record-list">
            <li v-for="record in visibleRecords" :key="record.id" class="record-row">{{ record.label }}</li>
          </ol>
        </div>
      </section>

      <section v-else-if="route === 'activity'" id="activity" aria-labelledby="activity-title">
        <div class="heading"><div><p class="eyebrow">Workspace</p><h1 id="activity-title">Team activity</h1><p>A shared record of progress across every project.</p></div><span class="count">{{ activities.length }} updates</span></div>
        <div class="activity-layout">
          <section class="panel activity-panel" aria-label="All activity"><div class="activity-date"><span>Today</span><span class="line" /></div><ActivityList :items="activities" /></section>
          <aside class="activity-summary">
            <section class="panel summary-card"><p class="eyebrow">Last 7 days</p><strong>42</strong><span>team updates</span><div class="mini-bars" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /></div></section>
            <section class="panel contributor-card"><p class="eyebrow">Top contributors</p><div><span class="avatar" data-person="norm-barlug">NB</span><a href="#/teams/norm-barlug">Norm Barlug</a><em>14</em></div><div><span class="avatar" data-person="emmy-nother">EN</span><a href="#/teams/emmy-nother">Emmy Nother</a><em>11</em></div><div><span class="avatar" data-person="fazlo-kan">FK</span><a href="#/teams/fazlo-kan">Fazlo Kan</a><em>9</em></div></section>
          </aside>
        </div>
      </section>

      <section v-else id="teams">
        <div v-if="!selectedMember">
          <div class="heading"><div><p class="eyebrow">Manage</p><h1 id="teams-title">Manage teams</h1><p>Invite people and organize how your workspace collaborates.</p></div><span class="count">{{ members.length }} members</span></div>
          <section class="panel member-directory" aria-labelledby="member-list-title">
            <div class="heading"><div><h2 id="member-list-title">All team members</h2><p>Everyone with access to the Luminate workspace.</p></div><span>Team</span><span>Role</span></div>
            <div class="member-list">
              <article v-for="member in members" :key="member.id" class="member-row"><span class="avatar" :data-person="member.id">{{ member.initials }}</span><div class="identity"><a :href="`#/teams/${member.id}`">{{ member.name }}</a><span>{{ member.email }}</span></div><span class="team">{{ member.team }}</span><span class="role">{{ member.role }}</span></article>
            </div>
          </section>
          <section class="team-actions">
            <div class="heading"><div><h2>Team actions</h2><p>Invitations and new teams require a connected server.</p></div></div>
            <div class="forms">
              <form class="panel team-form" novalidate @submit.prevent="submitInvite">
                <div class="heading"><span class="icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3" /><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M17.5 8v6M14.5 11h6" /></svg></span><div><h2>Invite a teammate</h2><p>Send an invitation to join Luminate.</p></div></div>
                <label class="field"><span>Email address</span><input type="email" name="email" placeholder="name@company.com" aria-describedby="invite-email-error" :aria-invalid="emailError ? 'true' : undefined" required @input="updateEmailError"><small id="invite-email-error" class="error" aria-live="polite" :hidden="!emailError">{{ emailError }}</small></label>
                <label class="field"><span>Role</span><select name="role"><option>Member</option><option>Admin</option><option>Viewer</option></select></label>
                <button class="primary-button" type="submit">Send invitation</button>
              </form>
              <form class="panel team-form" novalidate @submit.prevent="showToast">
                <div class="heading"><span class="icon" data-form-kind="create-team" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="8" cy="8" r="3" /><circle cx="17" cy="9" r="2.5" /><path d="M2.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M14 14c3.8-.7 6.2 1 6.8 5" /></svg></span><div><h2>Create a team</h2><p>Group teammates around a shared area of work.</p></div></div>
                <label class="field"><span>Team name</span><input type="text" name="teamName" placeholder="e.g. Product design" required></label>
                <label class="field"><span>Description <em>Optional</em></span><textarea name="description" rows="3" placeholder="What does this team work on?" /></label>
                <button class="primary-button" type="submit">Create team</button>
              </form>
            </div>
          </section>
        </div>

        <div v-else id="profile">
          <a class="back-link" href="#/teams"><span aria-hidden="true">←</span> All team members</a>
          <article class="panel member-profile-card">
            <div class="header"><span class="avatar large" :data-person="selectedMember.id">{{ selectedMember.initials }}</span><div><p class="eyebrow">{{ selectedMember.team }}</p><h1>{{ selectedMember.name }}</h1><span>{{ selectedMember.role }}</span></div></div>
            <p class="bio">{{ selectedMember.bio }}</p>
            <dl class="member-details"><div><dt>Email</dt><dd><a :href="`mailto:${selectedMember.email}`">{{ selectedMember.email }}</a></dd></div><div><dt>Country</dt><dd>{{ selectedMember.country }}</dd></div><div><dt>Team</dt><dd>{{ selectedMember.team }}</dd></div></dl>
          </article>
        </div>

        <div id="toasts" aria-live="polite" aria-label="Notifications">
          <div v-for="toast in toasts" :key="toast.id" class="toast"><span class="icon" aria-hidden="true">!</span><span class="message">{{ toast.message }}</span><button type="button" aria-label="Dismiss notification" @click="dismissToast(toast.id)">×</button></div>
        </div>
      </section>
    </main>
  </div>
</template>
