// examples/framework-spa/vue/src/App.vue
<script setup lang="ts">
import {computed, onBeforeUnmount, onMounted, ref, watch} from 'vue'
import ActivityList from './components/ActivityList.vue'
import ProjectCards from './components/ProjectCards.vue'
import {
  activities,
  documentTitle,
  memberFromHash,
  members,
  metrics,
  normalizeHash,
  projects,
  routeFromHash,
  type ProjectFilter,
  type Toast,
} from '../../shared/data'

normalizeHash()

const route = ref(routeFromHash(location.hash))
const memberId = ref(memberFromHash(location.hash))
const navOpen = ref(false)
const filter = ref<ProjectFilter>('all')
const toasts = ref<Toast[]>([])
const emailError = ref('')
let nextToastId = 1
const toastTimers = new Map<string, number>()

const selectedMember = computed(() => members.find(member => member.id === memberId.value))
const visibleProjects = computed(() => projects.filter(project => {
  return filter.value === 'all' || project.status.toLowerCase() === filter.value
}))

function handleHashChange() {
  route.value = routeFromHash(location.hash)
  memberId.value = memberFromHash(location.hash)
  navOpen.value = false
  toasts.value = []
  document.querySelector<HTMLElement>('main')?.focus({preventScroll: true})
}

function closeIfCurrent(name: typeof route.value) {
  if (route.value === name) navOpen.value = false
}

function showToast() {
  const toast = {id: `demo-toast-${nextToastId++}`, message: 'No server for demo'}
  toasts.value.push(toast)
  toastTimers.set(toast.id, window.setTimeout(() => dismissToast(toast.id), 3200))
}

function dismissToast(id: string) {
  clearTimeout(toastTimers.get(id))
  toastTimers.delete(id)
  toasts.value = toasts.value.filter(toast => toast.id !== id)
}

function validateEmail(input: HTMLInputElement) {
  return input.validity.valueMissing
    ? 'Enter an email address.'
    : input.validity.typeMismatch
      ? 'Enter a valid email address.'
      : ''
}

function submitInvite(event: Event) {
  const form = event.currentTarget as HTMLFormElement
  const input = form.elements.namedItem('email') as HTMLInputElement
  input.value = input.value.trim()
  emailError.value = validateEmail(input)
  if (emailError.value) {
    input.focus()
    return
  }
  showToast()
}

function updateEmailError(event: Event) {
  if (emailError.value) emailError.value = validateEmail(event.currentTarget as HTMLInputElement)
}

watch([route, memberId], () => {
  document.title = documentTitle(route.value, memberId.value)
}, {immediate: true})

onMounted(() => addEventListener('hashchange', handleHashChange))
onBeforeUnmount(() => {
  removeEventListener('hashchange', handleHashChange)
  toastTimers.forEach(timer => clearTimeout(timer))
})
</script>

<template>
  <div :class="['app-shell', {'nav-open': navOpen}]">
    <header class="topbar">
      <div class="topbar__start">
        <button class="icon-button menu-button" type="button" aria-label="Open navigation" aria-controls="primary-navigation" :aria-expanded="navOpen" @click="navOpen = !navOpen">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16" /></svg>
        </button>
        <a class="brand" href="#/overview" aria-label="Luminate overview">
          <svg class="brand__mark" viewBox="0 0 36 36" aria-hidden="true"><path d="M18 3l3.6 11.4L33 18l-11.4 3.6L18 33l-3.6-11.4L3 18l11.4-3.6L18 3Z" /><circle cx="18" cy="18" r="3.8" /></svg>
          <span>luminate</span>
        </a>
        <span class="topbar__divider" aria-hidden="true" />
        <div class="workspace-switcher"><span class="workspace-avatar">N</span><span>Luminate</span></div>
      </div>
      <div class="topbar__end"><a class="user-menu" href="#/teams/freddy-fraggin"><span class="user-avatar">FF</span><span class="user-name">Freddy Fraggin</span></a></div>
    </header>

    <aside class="sidebar">
      <nav class="navigation" id="primary-navigation" aria-label="Primary navigation">
        <div class="navigation__body">
          <p class="navigation__eyebrow">Workspace</p>
          <a class="nav-link" href="#/overview" :aria-current="route === 'overview' ? 'page' : undefined" @click="closeIfCurrent('overview')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="6" height="6" rx="1" /><rect x="14" y="4" width="6" height="6" rx="1" /><rect x="4" y="14" width="6" height="6" rx="1" /><rect x="14" y="14" width="6" height="6" rx="1" /></svg>
            <span>Overview</span>
          </a>
          <a class="nav-link" href="#/projects" :aria-current="route === 'projects' ? 'page' : undefined" @click="closeIfCurrent('projects')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z" /></svg>
            <span>Projects</span><span class="nav-link__count">{{ projects.length }}</span>
          </a>
          <a class="nav-link" href="#/activity" :aria-current="route === 'activity' ? 'page' : undefined" @click="closeIfCurrent('activity')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h3l2-6 4 12 2-6h5" /></svg><span>Activity</span>
          </a>
          <p class="navigation__eyebrow navigation__eyebrow--spaced">Manage</p>
          <a class="nav-link" href="#/teams" :aria-current="route === 'teams' ? 'page' : undefined" @click="closeIfCurrent('teams')">
            <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3" /><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M16 8h5M18.5 5.5v5" /></svg><span>Teams</span>
          </a>
        </div>
      </nav>
    </aside>

    <button class="nav-backdrop" type="button" aria-label="Close navigation" @click="navOpen = false" />

    <main class="main-content" id="main-content" tabindex="-1">
      <section v-if="route === 'overview'" class="page" aria-labelledby="overview-title">
        <div class="page-heading">
          <div><p class="eyebrow">Friday, July 24</p><h1 id="overview-title">Good morning, Freddy</h1><p>Here's what's happening across your workspace today.</p></div>
          <a class="primary-button" href="#/projects"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z" /></svg>View projects</a>
        </div>
        <div class="metric-grid">
          <article v-for="metric in metrics" :key="metric.id" :class="['metric-card', {'metric-card--positive': metric.direction === 'positive'}]">
            <div class="metric-card__top"><span>{{ metric.label }}</span></div><strong>{{ metric.value }}</strong><span class="metric-card__change">{{ metric.change }}</span>
          </article>
        </div>
        <div class="section-heading"><div><h2>In focus</h2><p>Your team's most active projects.</p></div><a class="text-link" href="#/projects">View all <span aria-hidden="true">→</span></a></div>
        <ProjectCards :items="projects.slice(0, 3)" overview />
        <div class="overview-lower">
          <section class="panel activity-panel" aria-labelledby="recent-activity-title">
            <div class="panel__heading"><div><h2 id="recent-activity-title">Recent activity</h2><p>The latest updates from your team.</p></div><a class="text-link" href="#/activity">See all</a></div>
            <ActivityList :items="activities.slice(0, 3)" compact />
          </section>
          <aside class="panel week-card" aria-labelledby="week-title">
            <div class="week-card__top"><p class="eyebrow">This week</p><h2 id="week-title">Strong momentum</h2><p>Your team completed 28% more work than last week.</p></div>
            <div class="week-chart" aria-label="Weekly activity chart">
              <span style="height:42%"><i>Mon</i></span><span style="height:67%"><i>Tue</i></span><span style="height:55%"><i>Wed</i></span><span style="height:88%"><i>Thu</i></span><span class="is-today" style="height:76%"><i>Fri</i></span><span style="height:24%"><i>Sat</i></span><span style="height:18%"><i>Sun</i></span>
            </div>
          </aside>
        </div>
      </section>

      <section v-else-if="route === 'projects'" class="page" aria-labelledby="projects-title">
        <div class="page-heading"><div><p class="eyebrow">Workspace</p><h1 id="projects-title">Projects</h1><p>Plan work, track progress, and keep the team aligned.</p></div></div>
        <div class="project-toolbar">
          <div class="filter-group" aria-label="Filter projects">
            <button v-for="value in (['all', 'active', 'planning'] as const)" :key="value" type="button" :aria-pressed="filter === value" @click="filter = value">{{ value[0].toUpperCase() + value.slice(1) }}</button>
          </div>
          <p>{{ visibleProjects.length }} {{ visibleProjects.length === 1 ? 'project' : 'projects' }} shown</p>
        </div>
        <ProjectCards :items="visibleProjects" />
      </section>

      <section v-else-if="route === 'activity'" class="page" aria-labelledby="activity-title">
        <div class="page-heading"><div><p class="eyebrow">Workspace</p><h1 id="activity-title">Team activity</h1><p>A shared record of progress across every project.</p></div><span class="count-chip">{{ activities.length }} updates</span></div>
        <div class="activity-layout">
          <section class="panel activity-panel activity-panel--page" aria-label="All activity"><div class="activity-date"><span>Today</span><span class="activity-date__line" /></div><ActivityList :items="activities" /></section>
          <aside class="activity-summary">
            <section class="panel summary-card"><p class="eyebrow">Last 7 days</p><strong>42</strong><span>team updates</span><div class="mini-bars" aria-hidden="true"><i style="height:30%" /><i style="height:55%" /><i style="height:42%" /><i style="height:75%" /><i style="height:100%" /><i style="height:62%" /><i style="height:80%" /></div></section>
            <section class="panel contributor-card"><p class="eyebrow">Top contributors</p><div><span class="tiny-avatar tiny-avatar--purple">NB</span><a href="#/teams/norm-barlug">Norm Barlug</a><em>14</em></div><div><span class="tiny-avatar tiny-avatar--green">EN</span><a href="#/teams/emmy-nother">Emmy Nother</a><em>11</em></div><div><span class="tiny-avatar tiny-avatar--orange">FK</span><a href="#/teams/fazlo-kan">Fazlo Kan</a><em>9</em></div></section>
          </aside>
        </div>
      </section>

      <section v-else class="page">
        <div v-if="!selectedMember">
          <div class="page-heading"><div><p class="eyebrow">Manage</p><h1 id="teams-title">Manage teams</h1><p>Invite people and organize how your workspace collaborates.</p></div><span class="count-chip">{{ members.length }} members</span></div>
          <section class="panel member-directory" aria-labelledby="member-list-title">
            <div class="member-directory__heading"><div><h2 id="member-list-title">All team members</h2><p>Everyone with access to the Luminate workspace.</p></div><span>Team</span><span>Role</span></div>
            <div class="member-list">
              <article v-for="member in members" :key="member.id" class="member-row"><span class="member-avatar" :style="{backgroundColor: member.tone}">{{ member.initials }}</span><div class="member-row__identity"><a :href="`#/teams/${member.id}`">{{ member.name }}</a><span>{{ member.email }}</span></div><span class="member-row__team">{{ member.team }}</span><span class="member-row__role">{{ member.role }}</span></article>
            </div>
          </section>
          <div class="section-heading team-actions-heading"><div><h2>Team actions</h2><p>Invitations and new teams require a connected server.</p></div></div>
          <div class="team-form-grid">
            <form class="panel team-form" novalidate @submit.prevent="submitInvite">
              <div class="team-form__heading"><span class="team-form__icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3" /><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M17.5 8v6M14.5 11h6" /></svg></span><div><h2>Invite a teammate</h2><p>Send an invitation to join Luminate.</p></div></div>
              <label class="form-field"><span>Email address</span><input type="email" name="email" placeholder="name@company.com" aria-describedby="invite-email-error" :aria-invalid="emailError ? 'true' : undefined" required @input="updateEmailError"><small id="invite-email-error" class="form-field__error" aria-live="polite" :hidden="!emailError">{{ emailError }}</small></label>
              <label class="form-field"><span>Role</span><select name="role"><option>Member</option><option>Admin</option><option>Viewer</option></select></label>
              <button class="primary-button" type="submit">Send invitation</button>
            </form>
            <form class="panel team-form" novalidate @submit.prevent="showToast">
              <div class="team-form__heading"><span class="team-form__icon team-form__icon--orange" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="8" cy="8" r="3" /><circle cx="17" cy="9" r="2.5" /><path d="M2.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M14 14c3.8-.7 6.2 1 6.8 5" /></svg></span><div><h2>Create a team</h2><p>Group teammates around a shared area of work.</p></div></div>
              <label class="form-field"><span>Team name</span><input type="text" name="teamName" placeholder="e.g. Product design" required></label>
              <label class="form-field"><span>Description <em>Optional</em></span><textarea name="description" rows="3" placeholder="What does this team work on?" /></label>
              <button class="primary-button" type="submit">Create team</button>
            </form>
          </div>
        </div>

        <div v-else class="member-profile">
          <a class="back-link" href="#/teams"><span aria-hidden="true">←</span> All team members</a>
          <article class="panel member-profile-card">
            <div class="member-profile-card__header"><span class="member-avatar member-avatar--large" :style="{backgroundColor: selectedMember.tone}">{{ selectedMember.initials }}</span><div><p class="eyebrow">{{ selectedMember.team }}</p><h1>{{ selectedMember.name }}</h1><span>{{ selectedMember.role }}</span></div></div>
            <p class="member-profile-card__bio">{{ selectedMember.bio }}</p>
            <dl class="member-details"><div><dt>Email</dt><dd><a :href="`mailto:${selectedMember.email}`">{{ selectedMember.email }}</a></dd></div><div><dt>Country</dt><dd>{{ selectedMember.country }}</dd></div><div><dt>Team</dt><dd>{{ selectedMember.team }}</dd></div></dl>
          </article>
        </div>

        <div class="demo-toast-region" aria-live="polite" aria-label="Notifications">
          <div v-for="toast in toasts" :key="toast.id" class="demo-toast"><span class="demo-toast__icon" aria-hidden="true">!</span><span>{{ toast.message }}</span><button type="button" aria-label="Dismiss notification" @click="dismissToast(toast.id)">×</button></div>
        </div>
      </section>
    </main>
  </div>
</template>

// examples/framework-spa/angular/src/app/app.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  effect,
  inject,
  signal,
} from '@angular/core'
import {NgTemplateOutlet} from '@angular/common'
import {
  activities,
  documentTitle,
  memberFromHash,
  members,
  metrics,
  normalizeHash,
  projects,
  routeFromHash,
  type ProjectFilter,
  type Route,
  type Toast,
} from '../../../shared/data'

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [NgTemplateOutlet],
  templateUrl: './app.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  readonly projects = projects
  readonly activities = activities
  readonly members = members
  readonly metrics = metrics
  readonly filters: readonly ProjectFilter[] = ['all', 'active', 'planning']
  readonly weeklyBars = [
    {day: 'Mon', height: 42},
    {day: 'Tue', height: 67},
    {day: 'Wed', height: 55},
    {day: 'Thu', height: 88},
    {day: 'Fri', height: 76},
    {day: 'Sat', height: 24},
    {day: 'Sun', height: 18},
  ] as const
  readonly miniBars = [30, 55, 42, 75, 100, 62, 80]

  readonly route = signal<Route>('overview')
  readonly memberId = signal<string | null>(null)
  readonly navOpen = signal(false)
  readonly filter = signal<ProjectFilter>('all')
  readonly toasts = signal<Toast[]>([])
  readonly emailError = signal('')

  readonly selectedMember = computed(() => {
    return this.members.find(member => member.id === this.memberId())
  })
  readonly visibleProjects = computed(() => {
    return this.projects.filter(project => {
      return this.filter() === 'all'
        || project.status.toLowerCase() === this.filter()
    })
  })

  private readonly destroyRef = inject(DestroyRef)
  private readonly toastTimers = new Map<string, number>()
  private nextToastId = 1

  constructor() {
    normalizeHash()
    this.readHash()

    const handleHashChange = () => {
      this.readHash()
      this.navOpen.set(false)
      this.toasts.set([])
      document.querySelector<HTMLElement>('main')?.focus({preventScroll: true})
    }

    addEventListener('hashchange', handleHashChange)
    this.destroyRef.onDestroy(() => {
      removeEventListener('hashchange', handleHashChange)
      this.toastTimers.forEach(timer => clearTimeout(timer))
    })

    effect(() => {
      document.title = documentTitle(this.route(), this.memberId())
    })
  }

  closeIfCurrent(route: Route): void {
    if (this.route() === route) this.navOpen.set(false)
  }

  setFilter(filter: ProjectFilter): void {
    this.filter.set(filter)
  }

  submitInvite(event: SubmitEvent): void {
    event.preventDefault()
    const form = event.currentTarget as HTMLFormElement
    const input = form.elements.namedItem('email') as HTMLInputElement
    input.value = input.value.trim()
    const message = this.validationMessage(input)
    this.emailError.set(message)

    if (message !== '') {
      input.focus()
      return
    }
    this.showToast()
  }

  submitDemo(event: SubmitEvent): void {
    event.preventDefault()
    this.showToast()
  }

  updateEmailError(event: Event): void {
    if (this.emailError() !== '') {
      this.emailError.set(this.validationMessage(event.currentTarget as HTMLInputElement))
    }
  }

  showToast(): void {
    const toast = {
      id: `demo-toast-${this.nextToastId++}`,
      message: 'No server for demo',
    }
    this.toasts.update(items => [...items, toast])
    this.toastTimers.set(
      toast.id,
      window.setTimeout(() => this.dismissToast(toast.id), 3200),
    )
  }

  dismissToast(id: string): void {
    clearTimeout(this.toastTimers.get(id))
    this.toastTimers.delete(id)
    this.toasts.update(items => items.filter(item => item.id !== id))
  }

  private readHash(): void {
    this.route.set(routeFromHash(location.hash))
    this.memberId.set(memberFromHash(location.hash))
  }

  private validationMessage(input: HTMLInputElement): string {
    if (input.validity.valueMissing) return 'Enter an email address.'
    if (input.validity.typeMismatch) return 'Enter a valid email address.'
    return ''
  }
}

<div class="app-shell" [class.nav-open]="navOpen()">
  <header class="topbar">
    <div class="topbar__start">
      <button class="icon-button menu-button" type="button" aria-label="Open navigation" aria-controls="primary-navigation" [attr.aria-expanded]="navOpen()" (click)="navOpen.set(!navOpen())">
        <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7h16M4 12h16M4 17h16"></path></svg>
      </button>
      <a class="brand" href="#/overview" aria-label="Luminate overview">
        <svg class="brand__mark" viewBox="0 0 36 36" aria-hidden="true"><path d="M18 3l3.6 11.4L33 18l-11.4 3.6L18 33l-3.6-11.4L3 18l11.4-3.6L18 3Z"></path><circle cx="18" cy="18" r="3.8"></circle></svg>
        <span>luminate</span>
      </a>
      <span class="topbar__divider" aria-hidden="true"></span>
      <div class="workspace-switcher"><span class="workspace-avatar">N</span><span>Luminate</span></div>
    </div>
    <div class="topbar__end"><a class="user-menu" href="#/teams/freddy-fraggin"><span class="user-avatar">FF</span><span class="user-name">Freddy Fraggin</span></a></div>
  </header>

  <aside class="sidebar">
    <nav class="navigation" id="primary-navigation" aria-label="Primary navigation">
      <div class="navigation__body">
        <p class="navigation__eyebrow">Workspace</p>
        <a class="nav-link" href="#/overview" [attr.aria-current]="route() === 'overview' ? 'page' : null" (click)="closeIfCurrent('overview')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="6" height="6" rx="1"></rect><rect x="14" y="4" width="6" height="6" rx="1"></rect><rect x="4" y="14" width="6" height="6" rx="1"></rect><rect x="14" y="14" width="6" height="6" rx="1"></rect></svg>
          <span>Overview</span>
        </a>
        <a class="nav-link" href="#/projects" [attr.aria-current]="route() === 'projects' ? 'page' : null" (click)="closeIfCurrent('projects')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z"></path></svg>
          <span>Projects</span><span class="nav-link__count">{{ projects.length }}</span>
        </a>
        <a class="nav-link" href="#/activity" [attr.aria-current]="route() === 'activity' ? 'page' : null" (click)="closeIfCurrent('activity')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h3l2-6 4 12 2-6h5"></path></svg><span>Activity</span>
        </a>
        <p class="navigation__eyebrow navigation__eyebrow--spaced">Manage</p>
        <a class="nav-link" href="#/teams" [attr.aria-current]="route() === 'teams' ? 'page' : null" (click)="closeIfCurrent('teams')">
          <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M16 8h5M18.5 5.5v5"></path></svg><span>Teams</span>
        </a>
      </div>
    </nav>
  </aside>

  <button class="nav-backdrop" type="button" aria-label="Close navigation" (click)="navOpen.set(false)"></button>

  <main class="main-content" id="main-content" tabindex="-1">
    @if (route() === 'overview') {
      <section class="page" aria-labelledby="overview-title">
        <div class="page-heading">
          <div><p class="eyebrow">Friday, July 24</p><h1 id="overview-title">Good morning, Freddy</h1><p>Here's what's happening across your workspace today.</p></div>
          <a class="primary-button" href="#/projects"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 7.5h6l2-2h8v14H4v-12Z"></path></svg>View projects</a>
        </div>
        <div class="metric-grid">
          @for (metric of metrics; track metric.id) {
            <article class="metric-card" [class.metric-card--positive]="metric.direction === 'positive'">
              <div class="metric-card__top"><span>{{ metric.label }}</span></div><strong>{{ metric.value }}</strong><span class="metric-card__change">{{ metric.change }}</span>
            </article>
          }
        </div>
        <div class="section-heading"><div><h2>In focus</h2><p>Your team's most active projects.</p></div><a class="text-link" href="#/projects">View all <span aria-hidden="true">→</span></a></div>
        <div class="project-grid project-grid--overview">
          @for (project of projects.slice(0, 3); track project.id) {
            <ng-container [ngTemplateOutlet]="projectCard" [ngTemplateOutletContext]="{$implicit: project}"></ng-container>
          }
        </div>
        <div class="overview-lower">
          <section class="panel activity-panel" aria-labelledby="recent-activity-title">
            <div class="panel__heading"><div><h2 id="recent-activity-title">Recent activity</h2><p>The latest updates from your team.</p></div><a class="text-link" href="#/activity">See all</a></div>
            <ol class="activity-list activity-list--compact">
              @for (activity of activities.slice(0, 3); track activity.id) {
                <ng-container [ngTemplateOutlet]="activityItem" [ngTemplateOutletContext]="{$implicit: activity}"></ng-container>
              }
            </ol>
          </section>
          <aside class="panel week-card" aria-labelledby="week-title">
            <div class="week-card__top"><p class="eyebrow">This week</p><h2 id="week-title">Strong momentum</h2><p>Your team completed 28% more work than last week.</p></div>
            <div class="week-chart" aria-label="Weekly activity chart">
              @for (bar of weeklyBars; track bar.day) {
                <span [class.is-today]="bar.day === 'Fri'" [style.height.%]="bar.height"><i>{{ bar.day }}</i></span>
              }
            </div>
          </aside>
        </div>
      </section>
    } @else if (route() === 'projects') {
      <section class="page" aria-labelledby="projects-title">
        <div class="page-heading"><div><p class="eyebrow">Workspace</p><h1 id="projects-title">Projects</h1><p>Plan work, track progress, and keep the team aligned.</p></div></div>
        <div class="project-toolbar">
          <div class="filter-group" aria-label="Filter projects">
            @for (value of filters; track value) {
              <button type="button" [attr.aria-pressed]="filter() === value" (click)="setFilter(value)">{{ value[0].toUpperCase() + value.slice(1) }}</button>
            }
          </div>
          <p>{{ visibleProjects().length }} {{ visibleProjects().length === 1 ? 'project' : 'projects' }} shown</p>
        </div>
        <div class="project-grid">
          @for (project of visibleProjects(); track project.id) {
            <ng-container [ngTemplateOutlet]="projectCard" [ngTemplateOutletContext]="{$implicit: project}"></ng-container>
          }
        </div>
      </section>
    } @else if (route() === 'activity') {
      <section class="page" aria-labelledby="activity-title">
        <div class="page-heading"><div><p class="eyebrow">Workspace</p><h1 id="activity-title">Team activity</h1><p>A shared record of progress across every project.</p></div><span class="count-chip">{{ activities.length }} updates</span></div>
        <div class="activity-layout">
          <section class="panel activity-panel activity-panel--page" aria-label="All activity">
            <div class="activity-date"><span>Today</span><span class="activity-date__line"></span></div>
            <ol class="activity-list">
              @for (activity of activities; track activity.id) {
                <ng-container [ngTemplateOutlet]="activityItem" [ngTemplateOutletContext]="{$implicit: activity}"></ng-container>
              }
            </ol>
          </section>
          <aside class="activity-summary">
            <section class="panel summary-card"><p class="eyebrow">Last 7 days</p><strong>42</strong><span>team updates</span><div class="mini-bars" aria-hidden="true">@for (height of miniBars; track $index) {<i [style.height.%]="height"></i>}</div></section>
            <section class="panel contributor-card"><p class="eyebrow">Top contributors</p><div><span class="tiny-avatar tiny-avatar--purple">NB</span><a href="#/teams/norm-barlug">Norm Barlug</a><em>14</em></div><div><span class="tiny-avatar tiny-avatar--green">EN</span><a href="#/teams/emmy-nother">Emmy Nother</a><em>11</em></div><div><span class="tiny-avatar tiny-avatar--orange">FK</span><a href="#/teams/fazlo-kan">Fazlo Kan</a><em>9</em></div></section>
          </aside>
        </div>
      </section>
    } @else {
      <section class="page">
        @if (selectedMember(); as member) {
          <div class="member-profile">
            <a class="back-link" href="#/teams"><span aria-hidden="true">←</span> All team members</a>
            <article class="panel member-profile-card">
              <div class="member-profile-card__header"><span class="member-avatar member-avatar--large" [style.background-color]="member.tone">{{ member.initials }}</span><div><p class="eyebrow">{{ member.team }}</p><h1>{{ member.name }}</h1><span>{{ member.role }}</span></div></div>
              <p class="member-profile-card__bio">{{ member.bio }}</p>
              <dl class="member-details"><div><dt>Email</dt><dd><a [href]="'mailto:' + member.email">{{ member.email }}</a></dd></div><div><dt>Country</dt><dd>{{ member.country }}</dd></div><div><dt>Team</dt><dd>{{ member.team }}</dd></div></dl>
            </article>
          </div>
        } @else {
          <div>
            <div class="page-heading"><div><p class="eyebrow">Manage</p><h1 id="teams-title">Manage teams</h1><p>Invite people and organize how your workspace collaborates.</p></div><span class="count-chip">{{ members.length }} members</span></div>
            <section class="panel member-directory" aria-labelledby="member-list-title">
              <div class="member-directory__heading"><div><h2 id="member-list-title">All team members</h2><p>Everyone with access to the Luminate workspace.</p></div><span>Team</span><span>Role</span></div>
              <div class="member-list">
                @for (member of members; track member.id) {
                  <article class="member-row"><span class="member-avatar" [style.background-color]="member.tone">{{ member.initials }}</span><div class="member-row__identity"><a [href]="'#/teams/' + member.id">{{ member.name }}</a><span>{{ member.email }}</span></div><span class="member-row__team">{{ member.team }}</span><span class="member-row__role">{{ member.role }}</span></article>
                }
              </div>
            </section>
            <div class="section-heading team-actions-heading"><div><h2>Team actions</h2><p>Invitations and new teams require a connected server.</p></div></div>
            <div class="team-form-grid">
              <form class="panel team-form" novalidate (submit)="submitInvite($event)">
                <div class="team-form__heading"><span class="team-form__icon" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"></circle><path d="M3.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M17.5 8v6M14.5 11h6"></path></svg></span><div><h2>Invite a teammate</h2><p>Send an invitation to join Luminate.</p></div></div>
                <label class="form-field"><span>Email address</span><input type="email" name="email" placeholder="name@company.com" aria-describedby="invite-email-error" [attr.aria-invalid]="emailError() ? 'true' : null" required (input)="updateEmailError($event)"><small id="invite-email-error" class="form-field__error" aria-live="polite" [hidden]="!emailError()">{{ emailError() }}</small></label>
                <label class="form-field"><span>Role</span><select name="role"><option>Member</option><option>Admin</option><option>Viewer</option></select></label>
                <button class="primary-button" type="submit">Send invitation</button>
              </form>
              <form class="panel team-form" novalidate (submit)="submitDemo($event)">
                <div class="team-form__heading"><span class="team-form__icon team-form__icon--orange" aria-hidden="true"><svg viewBox="0 0 24 24"><circle cx="8" cy="8" r="3"></circle><circle cx="17" cy="9" r="2.5"></circle><path d="M2.5 19c.5-4 2.3-6 5.5-6s5 2 5.5 6M14 14c3.8-.7 6.2 1 6.8 5"></path></svg></span><div><h2>Create a team</h2><p>Group teammates around a shared area of work.</p></div></div>
                <label class="form-field"><span>Team name</span><input type="text" name="teamName" placeholder="e.g. Product design" required></label>
                <label class="form-field"><span>Description <em>Optional</em></span><textarea name="description" rows="3" placeholder="What does this team work on?"></textarea></label>
                <button class="primary-button" type="submit">Create team</button>
              </form>
            </div>
          </div>
        }
        <div class="demo-toast-region" aria-live="polite" aria-label="Notifications">
          @for (toast of toasts(); track toast.id) {
            <div class="demo-toast"><span class="demo-toast__icon" aria-hidden="true">!</span><span>{{ toast.message }}</span><button type="button" aria-label="Dismiss notification" (click)="dismissToast(toast.id)">×</button></div>
          }
        </div>
      </section>
    }
  </main>
</div>

<ng-template #projectCard let-project>
  <article class="project-card">
    <div class="project-card__top"><span class="project-accent" [style.background-color]="project.accent"></span><span class="status" [class.status--planning]="project.status === 'Planning'">{{ project.status }}</span></div>
    <h3>{{ project.name }}</h3><p>{{ project.description }}</p>
    <div class="progress-label"><span>Progress</span><strong>{{ project.progress }}%</strong></div>
    <div class="progress-track"><span [style.width.%]="project.progress"></span></div>
    <div class="project-card__footer"><span class="member-stack">{{ project.members }}</span><span>{{ project.due }}</span></div>
  </article>
</ng-template>

<ng-template #activityItem let-activity>
  <li class="activity-item">
    <span class="activity-avatar" [style.background-color]="activity.tone">{{ activity.initials }}</span>
    <div class="activity-item__copy"><p><a class="person-link" [href]="'#/teams/' + activity.personId">{{ activity.person }}</a> <span>{{ activity.action }}</span> <b>{{ activity.target }}</b></p><time>{{ activity.time }}</time></div>
  </li>
</ng-template>
